/*
 * axxell-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.cinaq.axxell.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * An item is often equivalent to a product or service in your store
 */
@ApiModel(description = "An item is often equivalent to a product or service in your store")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-09-22T21:27:56.094+02:00")
public class Item   {
  @SerializedName("creationTime")
  private String creationTime = null;

  @SerializedName("itemId")
  private String itemId = null;

  @SerializedName("gid")
  private String gid = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("categories")
  private List<String> categories = new ArrayList<String>();

  @SerializedName("url")
  private String url = null;

  public Item creationTime(String creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * Read-only
   * @return creationTime
  **/
  @ApiModelProperty(example = "null", value = "Read-only")
  public String getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(String creationTime) {
    this.creationTime = creationTime;
  }

  public Item itemId(String itemId) {
    this.itemId = itemId;
    return this;
  }

   /**
   * This must be your product id used by your own store
   * @return itemId
  **/
  @ApiModelProperty(example = "null", value = "This must be your product id used by your own store")
  public String getItemId() {
    return itemId;
  }

  public void setItemId(String itemId) {
    this.itemId = itemId;
  }

  public Item gid(String gid) {
    this.gid = gid;
    return this;
  }

   /**
   * Global identifier of this item/product. Read-only
   * @return gid
  **/
  @ApiModelProperty(example = "null", value = "Global identifier of this item/product. Read-only")
  public String getGid() {
    return gid;
  }

  public void setGid(String gid) {
    this.gid = gid;
  }

  public Item title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Human readable title of the item/product
   * @return title
  **/
  @ApiModelProperty(example = "null", value = "Human readable title of the item/product")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Item label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Sanitized version of title. Read-only
   * @return label
  **/
  @ApiModelProperty(example = "null", value = "Sanitized version of title. Read-only")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public Item categories(List<String> categories) {
    this.categories = categories;
    return this;
  }

  public Item addCategoriesItem(String categoriesItem) {
    this.categories.add(categoriesItem);
    return this;
  }

   /**
   * Categories this item belongs to. List of keywords describing the item is also acceptable here.
   * @return categories
  **/
  @ApiModelProperty(example = "null", value = "Categories this item belongs to. List of keywords describing the item is also acceptable here.")
  public List<String> getCategories() {
    return categories;
  }

  public void setCategories(List<String> categories) {
    this.categories = categories;
  }

  public Item url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Full URL that links to the product. e.g. http://yourshop.com/product/123
   * @return url
  **/
  @ApiModelProperty(example = "null", value = "Full URL that links to the product. e.g. http://yourshop.com/product/123")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Item item = (Item) o;
    return Objects.equals(this.creationTime, item.creationTime) &&
        Objects.equals(this.itemId, item.itemId) &&
        Objects.equals(this.gid, item.gid) &&
        Objects.equals(this.title, item.title) &&
        Objects.equals(this.label, item.label) &&
        Objects.equals(this.categories, item.categories) &&
        Objects.equals(this.url, item.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creationTime, itemId, gid, title, label, categories, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Item {\n");
    
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    itemId: ").append(toIndentedString(itemId)).append("\n");
    sb.append("    gid: ").append(toIndentedString(gid)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

