/*
 * axxell-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.cinaq.axxell.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * A store is equivalent to an user account
 */
@ApiModel(description = "A store is equivalent to an user account")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-09-22T21:27:56.094+02:00")
public class Store   {
  @SerializedName("email")
  private String email = null;

  @SerializedName("apiKey")
  private String apiKey = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("salt")
  private String salt = null;

  @SerializedName("storeId")
  private String storeId = null;

  public Store email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Username/email used to login. Set this during registration.
   * @return email
  **/
  @ApiModelProperty(example = "null", required = true, value = "Username/email used to login. Set this during registration.")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public Store apiKey(String apiKey) {
    this.apiKey = apiKey;
    return this;
  }

   /**
   * Also known as secret key. Read-only
   * @return apiKey
  **/
  @ApiModelProperty(example = "null", value = "Also known as secret key. Read-only")
  public String getApiKey() {
    return apiKey;
  }

  public void setApiKey(String apiKey) {
    this.apiKey = apiKey;
  }

  public Store password(String password) {
    this.password = password;
    return this;
  }

   /**
   * The password required to login. Set this during registration.
   * @return password
  **/
  @ApiModelProperty(example = "null", value = "The password required to login. Set this during registration.")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public Store salt(String salt) {
    this.salt = salt;
    return this;
  }

   /**
   * Internal use
   * @return salt
  **/
  @ApiModelProperty(example = "null", value = "Internal use")
  public String getSalt() {
    return salt;
  }

  public void setSalt(String salt) {
    this.salt = salt;
  }

  public Store storeId(String storeId) {
    this.storeId = storeId;
    return this;
  }

   /**
   * Also known as access key. Read-only
   * @return storeId
  **/
  @ApiModelProperty(example = "null", value = "Also known as access key. Read-only")
  public String getStoreId() {
    return storeId;
  }

  public void setStoreId(String storeId) {
    this.storeId = storeId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Store store = (Store) o;
    return Objects.equals(this.email, store.email) &&
        Objects.equals(this.apiKey, store.apiKey) &&
        Objects.equals(this.password, store.password) &&
        Objects.equals(this.salt, store.salt) &&
        Objects.equals(this.storeId, store.storeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, apiKey, password, salt, storeId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Store {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    apiKey: ").append(toIndentedString(apiKey)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    salt: ").append(toIndentedString(salt)).append("\n");
    sb.append("    storeId: ").append(toIndentedString(storeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

